### ISSUE TITLE
Calculator program using Python

### ISSUE THREAD

**Issue by coding-vital** [coding-vital/HacktoberFestPython#1]
Create a simple calculator which can perform basic arithmetic operations like addition, subtraction, multiplication or division depending upon the user input.

Approach :

User choose the desired operation. Options 1, 2, 3 and 4 are valid.
Two numbers are taken and an if…elif…else branching is used to execute a particular section.
Using functions add(), subtract(), multiply() and divide() evaluate respective operations.

**Comment by Pankaj05011998** [comment]
Hey, can you assign this to me?

**Comment by Aayush-Bhatt** [comment]
I can work on this project as I have experience of it.

**Comment by coding-vital** [comment]
> I can work on this project as I have experience of it.

Go ahead.  I have assigned you the role

**Comment by coding-vital** [comment]
> Hey, can you assign this to me?

you can also go ahead. First come first serve

**Comment by sohamm20** [comment]
Hello. Please assign this to me
